version: '3.3'
services:
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server 

  autosketch-worker-parser:
    restart: always
    image: autodfir/autosketch:worker-parser-latest
    depends_on:
      - redis
    environment:
      - worker_num_env=2
    volumes:
      - ../etc:/etc/autosketch
      - /tmp/shared:/tmp #this is dirty solution, but it works 
      - /:/virt:ro # bad practice, but allows to upload to AS files directly from host

  autosketch-worker-uploader:
    restart: always
    image: autodfir/autosketch:worker-uploader-latest
    depends_on:
      - redis
    environment:
      - worker_num_env=2
    volumes:
      - ../etc:/etc/autosketch
      - /tmp/shared:/tmp #this is dirty solution, but it works
      - /:/virt:ro # bad practice, but allows to upload to AS files directly from host

  autosketch-webapp:
    restart: always
    ports:
      - '5001:5001'
    image: autodfir/autosketch:web-latest
    depends_on:
      - redis 

    volumes:
      - ./etc:/etc/autosketch
      - /tmp/shared:/tmp #shared volume between webapp and worker
      - /:/virt:ro # bad practice, but allows to upload to AS files directly from host
