REDIS_IP: 'redis'
REDIS_PORT: 6379
#Should be address accessible from outside
APP_IP: '0.0.0.0'
APP_PORT: 5001
#Should be address accessible from outside
TS_IP: '192.168.1.15'
TS_PORT: 80
TS_RC: /tmp/.timesketchrc
UPLOAD_FOLDER: '/tmp'

VELO_USED: false
S3_STS_USED: false
VELO_API_CONF_PATH: '/app/velo_api.config.yaml'
